version: '3.9'

services:
  mosquitto:
    image: eclipse-mosquitto:1.6 
    #network_mode: "host"
    ports:
      - 1883:1883
    restart: "unless-stopped"
    #user: 1000:1000
    volumes:
      #- '../cert:/cert'
      - './mosquitto.conf:/mosquitto/config/mosquitto.conf'
      - './password_file:/mosquitto/config/password_file'
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "10m"
